import { DM_Sans } from 'next/font/google';
import cx from 'classnames';
import type { Metadata } from 'next';

import { Header } from './components/Header';
import { Aside } from './components/Aside';

import './styles/globals.scss';

const dmSans = DM_Sans({
    subsets: ['latin'],
    variable: '--font-dm-sans',
});

export const metadata: Metadata = {
    title: 'React Frontend Developer',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={cx([dmSans.variable, 'dh-body font-dm-sans'])}>
                <Header />
                <Aside />
                <main className="dh-main">{children}</main>
            </body>
        </html>
    );
}
